spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://mongo-auth:27017/authdb}

jwt:
  secret: ${JWT_SECRET:yazlab2-super-secret-key-change-in-prod-256bit}
  expiration-ms: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

server:
  port: 8081
