server.port=8080
spring.application.name=user-service
spring.data.mongodb.uri=${MONGO_URI:mongodb://mongo-user:27017/userdb}
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
