spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://mongo-product:27017/productdb}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

server:
  port: 8083
